// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\ActivitiesController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:75
 * @route "/reports/{report}"
 */
export const update = (args: { report: string | { id: string } } | [ report: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put","patch"],
    url: "/reports/{report}",
} satisfies RouteDefinition<["put","patch"]>

/**
 * @see \App\Http\Controllers\ActivitiesController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:75
 * @route "/reports/{report}"
 */
update.url = (args: { report: string | { id: string } } | [ report: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { report: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { report: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        report: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        report: typeof args.report === "object" ? args.report.id : args.report,
    }
    
    return update.definition.url
        .replace("{report}", parsedArgs.report.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ActivitiesController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:75
 * @route "/reports/{report}"
 */
update.put = (args: { report: string | { id: string } } | [ report: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\ActivitiesController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:75
 * @route "/reports/{report}"
 */
update.patch = (args: { report: string | { id: string } } | [ report: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})








/**
 * @see \App\Http\Controllers\ActivitiesController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:84
 * @route "/reports/{report}"
 */
export const destroy = (args: { report: string | { id: string } } | [ report: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/reports/{report}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ActivitiesController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:84
 * @route "/reports/{report}"
 */
destroy.url = (args: { report: string | { id: string } } | [ report: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { report: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { report: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        report: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        report: typeof args.report === "object" ? args.report.id : args.report,
    }
    
    return destroy.definition.url
        .replace("{report}", parsedArgs.report.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ActivitiesController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:84
 * @route "/reports/{report}"
 */
destroy.delete = (args: { report: string | { id: string } } | [ report: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})








/**
 * @see \App\Http\Controllers\ActivitiesController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:31
 * @route "/reports"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/reports",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ActivitiesController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:31
 * @route "/reports"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ActivitiesController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:31
 * @route "/reports"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ActivitiesController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:31
 * @route "/reports"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})









const reports = {
    update,
    destroy,
    index,
}

export default reports