// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\ShowSharedHandler::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShowSharedHandler.php:15
 * @route "/shares/{token}"
 */
export const show = (args: { token: string | number } | [ token: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/shares/{token}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ShowSharedHandler::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShowSharedHandler.php:15
 * @route "/shares/{token}"
 */
show.url = (args: { token: string | number } | [ token: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { token: args }
    }
    
    if (Array.isArray(args)) {
        args = {
        token: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        token: args.token,
    }
    
    return show.definition.url
        .replace("{token}", parsedArgs.token.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ShowSharedHandler::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShowSharedHandler.php:15
 * @route "/shares/{token}"
 */
show.get = (args: { token: string | number } | [ token: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ShowSharedHandler::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShowSharedHandler.php:15
 * @route "/shares/{token}"
 */
show.head = (args: { token: string | number } | [ token: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})









const shares = {
    show,
}

export default shares