// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\SharedController::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/SharedController.php:17
 * @route "/shares/{share}"
 */
export const show = (args: { share: string | { id: string } } | [ share: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/shares/{share}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\SharedController::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/SharedController.php:17
 * @route "/shares/{share}"
 */
show.url = (args: { share: string | { id: string } } | [ share: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { share: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { share: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        share: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        share: typeof args.share === "object" ? args.share.id : args.share,
    }
    
    return show.definition.url
        .replace("{share}", parsedArgs.share.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\SharedController::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/SharedController.php:17
 * @route "/shares/{share}"
 */
show.get = (args: { share: string | { id: string } } | [ share: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\SharedController::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/SharedController.php:17
 * @route "/shares/{share}"
 */
show.head = (args: { share: string | { id: string } } | [ share: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})









const shares = {
    show,
}

export default shares