// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\AuthController::redirect
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:23
 * @route "/login/redirect"
 */
export const redirect = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: redirect.url(options),
    method: "get",
})

redirect.definition = {
    methods: ["get","head"],
    url: "/login/redirect",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\AuthController::redirect
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:23
 * @route "/login/redirect"
 */
redirect.url = (options?: RouteQueryOptions) => {
    return redirect.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::redirect
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:23
 * @route "/login/redirect"
 */
redirect.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: redirect.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\AuthController::redirect
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:23
 * @route "/login/redirect"
 */
redirect.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: redirect.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\AuthController::callback
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:28
 * @route "/login/callback"
 */
export const callback = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: callback.url(options),
    method: "get",
})

callback.definition = {
    methods: ["get","head"],
    url: "/login/callback",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\AuthController::callback
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:28
 * @route "/login/callback"
 */
callback.url = (options?: RouteQueryOptions) => {
    return callback.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::callback
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:28
 * @route "/login/callback"
 */
callback.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: callback.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\AuthController::callback
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:28
 * @route "/login/callback"
 */
callback.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: callback.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\AuthController::disabled
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:54
 * @route "/login/disabled"
 */
export const disabled = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: disabled.url(options),
    method: "post",
})

disabled.definition = {
    methods: ["post"],
    url: "/login/disabled",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\AuthController::disabled
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:54
 * @route "/login/disabled"
 */
disabled.url = (options?: RouteQueryOptions) => {
    return disabled.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::disabled
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:54
 * @route "/login/disabled"
 */
disabled.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: disabled.url(options),
    method: "post",
})









const login = {
    redirect,
    callback,
    disabled,
}

export default login