// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\AuthController::disabled
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:50
 * @route "/login/disabled"
 */
export const disabled = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: disabled.url(options),
    method: "post",
})

disabled.definition = {
    methods: ["post"],
    url: "/login/disabled",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\AuthController::disabled
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:50
 * @route "/login/disabled"
 */
disabled.url = (options?: RouteQueryOptions) => {
    return disabled.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::disabled
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:50
 * @route "/login/disabled"
 */
disabled.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: disabled.url(options),
    method: "post",
})









const login = {
    disabled,
}

export default login