// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectInvoiceController.php:11
 * @route "/projects/{project}/invoices"
 */
export const store = (args: { project: string | number } | [ project: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/projects/{project}/invoices",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectInvoiceController.php:11
 * @route "/projects/{project}/invoices"
 */
store.url = (args: { project: string | number } | [ project: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: args.project,
    }
    
    return store.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectInvoiceController.php:11
 * @route "/projects/{project}/invoices"
 */
store.post = (args: { project: string | number } | [ project: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})









const invoices = {
    store,
}

export default invoices