// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\ReceivedShareController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ReceivedShareController.php:11
 * @route "/received-shares/{receivedShare}"
 */
export const destroy = (args: { receivedShare: string | { id: string } } | [ receivedShare: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/received-shares/{receivedShare}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ReceivedShareController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ReceivedShareController.php:11
 * @route "/received-shares/{receivedShare}"
 */
destroy.url = (args: { receivedShare: string | { id: string } } | [ receivedShare: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { receivedShare: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { receivedShare: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        receivedShare: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        receivedShare: typeof args.receivedShare === "object" ? args.receivedShare.id : args.receivedShare,
    }
    
    return destroy.definition.url
        .replace("{receivedShare}", parsedArgs.receivedShare.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ReceivedShareController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ReceivedShareController.php:11
 * @route "/received-shares/{receivedShare}"
 */
destroy.delete = (args: { receivedShare: string | { id: string } } | [ receivedShare: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})









const receivedShares = {
    destroy,
}

export default receivedShares