// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\ShowApiDocHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowApiDocHandler.php:11
 * @route "/docs/api"
 */
export const api = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: api.url(options),
    method: "get",
})

api.definition = {
    methods: ["get","head"],
    url: "/docs/api",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ShowApiDocHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowApiDocHandler.php:11
 * @route "/docs/api"
 */
api.url = (options?: RouteQueryOptions) => {
    return api.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ShowApiDocHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowApiDocHandler.php:11
 * @route "/docs/api"
 */
api.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: api.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ShowApiDocHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowApiDocHandler.php:11
 * @route "/docs/api"
 */
api.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: api.url(options),
    method: "head",
})









const docs = {
    api,
}

export default docs