// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\UserController::regenerateToken
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:46
 * @route "/profile/tokens"
 */
export const regenerate = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: regenerate.url(options),
    method: "post",
})

regenerate.definition = {
    methods: ["post"],
    url: "/profile/tokens",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\UserController::regenerateToken
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:46
 * @route "/profile/tokens"
 */
regenerate.url = (options?: RouteQueryOptions) => {
    return regenerate.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\UserController::regenerateToken
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:46
 * @route "/profile/tokens"
 */
regenerate.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: regenerate.url(options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\UserController::deleteToken
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:54
 * @route "/profile/tokens"
 */
export const destroy = (options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/profile/tokens",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\UserController::deleteToken
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:54
 * @route "/profile/tokens"
 */
destroy.url = (options?: RouteQueryOptions) => {
    return destroy.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\UserController::deleteToken
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:54
 * @route "/profile/tokens"
 */
destroy.delete = (options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(options),
    method: "delete",
})









const tokens = {
    regenerate,
    destroy,
}

export default tokens