// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";
import share from "./share";
import billing from "./billing";

/**
 * @see \App\Http\Controllers\ClientController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:19
 * @route "/clients/{client}/edit"
 */
export const edit = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(args, options),
    method: "get",
})

edit.definition = {
    methods: ["get","head"],
    url: "/clients/{client}/edit",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ClientController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:19
 * @route "/clients/{client}/edit"
 */
edit.url = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return edit.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:19
 * @route "/clients/{client}/edit"
 */
edit.get = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ClientController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:19
 * @route "/clients/{client}/edit"
 */
edit.head = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: edit.url(args, options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\ClientController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:33
 * @route "/clients/{client}"
 */
export const update = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put","patch"],
    url: "/clients/{client}",
} satisfies RouteDefinition<["put","patch"]>

/**
 * @see \App\Http\Controllers\ClientController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:33
 * @route "/clients/{client}"
 */
update.url = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return update.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:33
 * @route "/clients/{client}"
 */
update.put = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\ClientController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:33
 * @route "/clients/{client}"
 */
update.patch = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})








/**
 * @see \App\Http\Controllers\ClientController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:52
 * @route "/clients/{client}"
 */
export const destroy = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/clients/{client}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ClientController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:52
 * @route "/clients/{client}"
 */
destroy.url = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return destroy.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:52
 * @route "/clients/{client}"
 */
destroy.delete = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})








/**
 * @see \App\Http\Controllers\ClientController::restore
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:45
 * @route "/clients/{client}/restore"
 */
export const restore = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: restore.url(args, options),
    method: "post",
})

restore.definition = {
    methods: ["post"],
    url: "/clients/{client}/restore",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ClientController::restore
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:45
 * @route "/clients/{client}/restore"
 */
restore.url = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return restore.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::restore
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:45
 * @route "/clients/{client}/restore"
 */
restore.post = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: restore.url(args, options),
    method: "post",
})









const clients = {
    edit,
    update,
    destroy,
    restore,
    share,
    billing,
}

export default clients