// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\ClientController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:13
 * @route "/clients"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/clients",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ClientController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:13
 * @route "/clients"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:13
 * @route "/clients"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\ClientController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:23
 * @route "/clients/{client}"
 */
export const update = (args: { client: number | { id: number } } | [ client: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put","patch"],
    url: "/clients/{client}",
} satisfies RouteDefinition<["put","patch"]>

/**
 * @see \App\Http\Controllers\ClientController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:23
 * @route "/clients/{client}"
 */
update.url = (args: { client: number | { id: number } } | [ client: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return update.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:23
 * @route "/clients/{client}"
 */
update.put = (args: { client: number | { id: number } } | [ client: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\ClientController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:23
 * @route "/clients/{client}"
 */
update.patch = (args: { client: number | { id: number } } | [ client: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})








/**
 * @see \App\Http\Controllers\ClientController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:32
 * @route "/clients/{client}"
 */
export const destroy = (args: { client: number | { id: number } } | [ client: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/clients/{client}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ClientController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:32
 * @route "/clients/{client}"
 */
destroy.url = (args: { client: number | { id: number } } | [ client: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return destroy.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php:32
 * @route "/clients/{client}"
 */
destroy.delete = (args: { client: number | { id: number } } | [ client: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})









const clients = {
    store,
    update,
    destroy,
}

export default clients