// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import entries from "./entries";

export const projects = {
    entries,
}

export default projects