// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\BillingController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php:55
 * @route "/invoices/{invoice}"
 */
export const update = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put"],
    url: "/invoices/{invoice}",
} satisfies RouteDefinition<["put"]>

/**
 * @see \App\Http\Controllers\BillingController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php:55
 * @route "/invoices/{invoice}"
 */
update.url = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { invoice: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { invoice: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        invoice: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        invoice: typeof args.invoice === "object" ? args.invoice.id : args.invoice,
    }
    
    return update.definition.url
        .replace("{invoice}", parsedArgs.invoice.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BillingController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php:55
 * @route "/invoices/{invoice}"
 */
update.put = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})








/**
 * @see \App\Http\Controllers\BillingController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php:68
 * @route "/invoices/{invoice}"
 */
export const destroy = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/invoices/{invoice}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\BillingController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php:68
 * @route "/invoices/{invoice}"
 */
destroy.url = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { invoice: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { invoice: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        invoice: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        invoice: typeof args.invoice === "object" ? args.invoice.id : args.invoice,
    }
    
    return destroy.definition.url
        .replace("{invoice}", parsedArgs.invoice.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BillingController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php:68
 * @route "/invoices/{invoice}"
 */
destroy.delete = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})









const invoices = {
    update,
    destroy,
}

export default invoices