// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::store
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:12
 * @route "/projects/{project}/invoices"
 */
export const store = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/projects/{project}/invoices",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::store
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:12
 * @route "/projects/{project}/invoices"
 */
store.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return store.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::store
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:12
 * @route "/projects/{project}/invoices"
 */
store.post = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\ProjectInvoiceController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:24
 * @route "/invoices/{invoice}"
 */
export const update = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put"],
    url: "/invoices/{invoice}",
} satisfies RouteDefinition<["put"]>

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:24
 * @route "/invoices/{invoice}"
 */
update.url = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { invoice: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { invoice: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        invoice: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        invoice: typeof args.invoice === "object" ? args.invoice.id : args.invoice,
    }
    
    return update.definition.url
        .replace("{invoice}", parsedArgs.invoice.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:24
 * @route "/invoices/{invoice}"
 */
update.put = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})








/**
 * @see \App\Http\Controllers\ProjectInvoiceController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:36
 * @route "/invoices/{invoice}"
 */
export const destroy = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/invoices/{invoice}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:36
 * @route "/invoices/{invoice}"
 */
destroy.url = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { invoice: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { invoice: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        invoice: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        invoice: typeof args.invoice === "object" ? args.invoice.id : args.invoice,
    }
    
    return destroy.definition.url
        .replace("{invoice}", parsedArgs.invoice.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectInvoiceController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php:36
 * @route "/invoices/{invoice}"
 */
destroy.delete = (args: { invoice: string | { id: string } } | [ invoice: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})









const invoices = {
    store,
    update,
    destroy,
}

export default invoices