/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UApp: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDropdownMenu: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFooter: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UForm: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULink: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/vue/overrides/inertia/Link.vue')['default']
    UMain: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UModal: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    USelect: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USlideover: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTextarea: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
