// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see /Users/mathieutu/Projects/takt/vendor/laravel/boost/src/BoostServiceProvider.php:92
 * @route "/_boost/browser-logs"
 */
export const browserLogs = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: browserLogs.url(options),
    method: "post",
})

browserLogs.definition = {
    methods: ["post"],
    url: "/_boost/browser-logs",
} satisfies RouteDefinition<["post"]>

/**
 * @see /Users/mathieutu/Projects/takt/vendor/laravel/boost/src/BoostServiceProvider.php:92
 * @route "/_boost/browser-logs"
 */
browserLogs.url = (options?: RouteQueryOptions) => {
    return browserLogs.definition.url + queryParams(options)
}

/**
 * @see /Users/mathieutu/Projects/takt/vendor/laravel/boost/src/BoostServiceProvider.php:92
 * @route "/_boost/browser-logs"
 */
browserLogs.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: browserLogs.url(options),
    method: "post",
})









const boost = {
    "browser-logs": browserLogs,
}

export default boost