// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\UserController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:26
 * @route "/profile"
 */
export const update = (options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(options),
    method: "put",
})

update.definition = {
    methods: ["put"],
    url: "/profile",
} satisfies RouteDefinition<["put"]>

/**
 * @see \App\Http\Controllers\UserController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:26
 * @route "/profile"
 */
update.url = (options?: RouteQueryOptions) => {
    return update.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\UserController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:26
 * @route "/profile"
 */
update.put = (options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(options),
    method: "put",
})








/**
 * @see \App\Http\Controllers\UserController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:40
 * @route "/profile"
 */
export const destroy = (options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/profile",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\UserController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:40
 * @route "/profile"
 */
destroy.url = (options?: RouteQueryOptions) => {
    return destroy.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\UserController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:40
 * @route "/profile"
 */
destroy.delete = (options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(options),
    method: "delete",
})









const profile = {
    update,
    destroy,
}

export default profile