// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../index";

/**
 * @see /Users/mathieutu/Projects/takt/routes/web.php:62
 * @route "/up"
 */
export const up = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: up.url(options),
    method: "get",
})

up.definition = {
    methods: ["get","head"],
    url: "/up",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see /Users/mathieutu/Projects/takt/routes/web.php:62
 * @route "/up"
 */
up.url = (options?: RouteQueryOptions) => {
    return up.definition.url + queryParams(options)
}

/**
 * @see /Users/mathieutu/Projects/takt/routes/web.php:62
 * @route "/up"
 */
up.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: up.url(options),
    method: "get",
})

/**
 * @see /Users/mathieutu/Projects/takt/routes/web.php:62
 * @route "/up"
 */
up.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: up.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\ShowHomeHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowHomeHandler.php:17
 * @route "/"
 */
export const dashboard = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: dashboard.url(options),
    method: "get",
})

dashboard.definition = {
    methods: ["get","head"],
    url: "/",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ShowHomeHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowHomeHandler.php:17
 * @route "/"
 */
dashboard.url = (options?: RouteQueryOptions) => {
    return dashboard.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ShowHomeHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowHomeHandler.php:17
 * @route "/"
 */
dashboard.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: dashboard.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ShowHomeHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowHomeHandler.php:17
 * @route "/"
 */
dashboard.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: dashboard.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\AuthController::demo
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:65
 * @route "/demo"
 */
export const demo = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: demo.url(options),
    method: "get",
})

demo.definition = {
    methods: ["get","head"],
    url: "/demo",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\AuthController::demo
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:65
 * @route "/demo"
 */
demo.url = (options?: RouteQueryOptions) => {
    return demo.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::demo
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:65
 * @route "/demo"
 */
demo.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: demo.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\AuthController::demo
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:65
 * @route "/demo"
 */
demo.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: demo.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\AuthController::show
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:16
 * @route "/login"
 */
export const login = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: login.url(options),
    method: "get",
})

login.definition = {
    methods: ["get","head"],
    url: "/login",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\AuthController::show
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:16
 * @route "/login"
 */
login.url = (options?: RouteQueryOptions) => {
    return login.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::show
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:16
 * @route "/login"
 */
login.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: login.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\AuthController::show
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:16
 * @route "/login"
 */
login.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: login.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:78
 * @route "/logout"
 */
export const logout = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: logout.url(options),
    method: "get",
})

logout.definition = {
    methods: ["get","head"],
    url: "/logout",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:78
 * @route "/logout"
 */
logout.url = (options?: RouteQueryOptions) => {
    return logout.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:78
 * @route "/logout"
 */
logout.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: logout.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php:78
 * @route "/logout"
 */
logout.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: logout.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\UserController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:17
 * @route "/profile"
 */
export const profile = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: profile.url(options),
    method: "get",
})

profile.definition = {
    methods: ["get","head"],
    url: "/profile",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\UserController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:17
 * @route "/profile"
 */
profile.url = (options?: RouteQueryOptions) => {
    return profile.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\UserController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:17
 * @route "/profile"
 */
profile.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: profile.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\UserController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php:17
 * @route "/profile"
 */
profile.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: profile.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\ShowTimesheetHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowTimesheetHandler.php:18
 * @route "/timesheet"
 */
export const timesheet = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: timesheet.url(options),
    method: "get",
})

timesheet.definition = {
    methods: ["get","head"],
    url: "/timesheet",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ShowTimesheetHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowTimesheetHandler.php:18
 * @route "/timesheet"
 */
timesheet.url = (options?: RouteQueryOptions) => {
    return timesheet.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ShowTimesheetHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowTimesheetHandler.php:18
 * @route "/timesheet"
 */
timesheet.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: timesheet.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ShowTimesheetHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ShowTimesheetHandler.php:18
 * @route "/timesheet"
 */
timesheet.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: timesheet.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\CommandBarController::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/CommandBarController.php:10
 * @route "/command-bar"
 */
export const commandBar = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: commandBar.url(options),
    method: "get",
})

commandBar.definition = {
    methods: ["get","head"],
    url: "/command-bar",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\CommandBarController::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/CommandBarController.php:10
 * @route "/command-bar"
 */
commandBar.url = (options?: RouteQueryOptions) => {
    return commandBar.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\CommandBarController::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/CommandBarController.php:10
 * @route "/command-bar"
 */
commandBar.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: commandBar.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\CommandBarController::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/CommandBarController.php:10
 * @route "/command-bar"
 */
commandBar.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: commandBar.url(options),
    method: "head",
})









const routes = {
    up,
    dashboard,
    demo,
    login,
    logout,
    profile,
    timesheet,
    "command-bar": commandBar,
}

export default routes