// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../index";

/**
 * @see \App\Http\Controllers\AuthController::show
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:15
 * @route "/login"
 */
export const login = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: login.url(options),
    method: "get",
})

login.definition = {
    methods: ["get","head"],
    url: "/login",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\AuthController::show
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:15
 * @route "/login"
 */
login.url = (options?: RouteQueryOptions) => {
    return login.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::show
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:15
 * @route "/login"
 */
login.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: login.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\AuthController::show
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:15
 * @route "/login"
 */
login.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: login.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:60
 * @route "/logout"
 */
export const logout = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: logout.url(options),
    method: "post",
})

logout.definition = {
    methods: ["post","get","head"],
    url: "/logout",
} satisfies RouteDefinition<["post","get","head"]>

/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:60
 * @route "/logout"
 */
logout.url = (options?: RouteQueryOptions) => {
    return logout.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:60
 * @route "/logout"
 */
logout.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: logout.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:60
 * @route "/logout"
 */
logout.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: logout.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\AuthController::logout
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php:60
 * @route "/logout"
 */
logout.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: logout.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php:14
 * @route "/"
 */
export const home = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: home.url(options),
    method: "get",
})

home.definition = {
    methods: ["get","head"],
    url: "/",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php:14
 * @route "/"
 */
home.url = (options?: RouteQueryOptions) => {
    return home.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php:14
 * @route "/"
 */
home.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: home.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php:14
 * @route "/"
 */
home.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: home.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\UserController::edit
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php:13
 * @route "/profile"
 */
export const profile = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: profile.url(options),
    method: "get",
})

profile.definition = {
    methods: ["get","head"],
    url: "/profile",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\UserController::edit
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php:13
 * @route "/profile"
 */
profile.url = (options?: RouteQueryOptions) => {
    return profile.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\UserController::edit
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php:13
 * @route "/profile"
 */
profile.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: profile.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\UserController::edit
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php:13
 * @route "/profile"
 */
profile.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: profile.url(options),
    method: "head",
})









const routes = {
    login,
    logout,
    home,
    profile,
}

export default routes