// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\TrackingController::updateBilling
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:116
 * @route "/billing/{entry}"
 */
export const update = (args: { entry: number | { id: number } } | [ entry: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put"],
    url: "/billing/{entry}",
} satisfies RouteDefinition<["put"]>

/**
 * @see \App\Http\Controllers\TrackingController::updateBilling
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:116
 * @route "/billing/{entry}"
 */
update.url = (args: { entry: number | { id: number } } | [ entry: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { entry: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { entry: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        entry: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        entry: typeof args.entry === "object" ? args.entry.id : args.entry,
    }
    
    return update.definition.url
        .replace("{entry}", parsedArgs.entry.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\TrackingController::updateBilling
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:116
 * @route "/billing/{entry}"
 */
update.put = (args: { entry: number | { id: number } } | [ entry: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})









const billing = {
    update,
}

export default billing