// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ActivitiesController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:68
 * @route "/projects/{project}/reports"
 */
export const store = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/projects/{project}/reports",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ActivitiesController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:68
 * @route "/projects/{project}/reports"
 */
store.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return store.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ActivitiesController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:68
 * @route "/projects/{project}/reports"
 */
store.post = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\ActivitiesController::projectReports
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:18
 * @route "/projects/{project}/reports"
 */
export const index = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(args, options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/projects/{project}/reports",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ActivitiesController::projectReports
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:18
 * @route "/projects/{project}/reports"
 */
index.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return index.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ActivitiesController::projectReports
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:18
 * @route "/projects/{project}/reports"
 */
index.get = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ActivitiesController::projectReports
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ActivitiesController.php:18
 * @route "/projects/{project}/reports"
 */
index.head = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(args, options),
    method: "head",
})









const reports = {
    store,
    index,
}

export default reports