// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ClientController::storeShare
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:84
 * @route "/clients/{client}/share"
 */
export const store = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/clients/{client}/share",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ClientController::storeShare
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:84
 * @route "/clients/{client}/share"
 */
store.url = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return store.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::storeShare
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:84
 * @route "/clients/{client}/share"
 */
store.post = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\ClientController::destroyShare
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:93
 * @route "/clients/{client}/share"
 */
export const destroy = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/clients/{client}/share",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ClientController::destroyShare
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:93
 * @route "/clients/{client}/share"
 */
destroy.url = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return destroy.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::destroyShare
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:93
 * @route "/clients/{client}/share"
 */
destroy.delete = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})









const share = {
    store,
    destroy,
}

export default share