// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";
import entries from "./entries";

/**
 * @see \App\Http\Controllers\ProjectController::index
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:20
 * @route "/projects"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/projects",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ProjectController::index
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:20
 * @route "/projects"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::index
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:20
 * @route "/projects"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ProjectController::index
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:20
 * @route "/projects"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\ProjectController::create
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:40
 * @route "/projects/create"
 */
export const create = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: create.url(options),
    method: "get",
})

create.definition = {
    methods: ["get","head"],
    url: "/projects/create",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ProjectController::create
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:40
 * @route "/projects/create"
 */
create.url = (options?: RouteQueryOptions) => {
    return create.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::create
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:40
 * @route "/projects/create"
 */
create.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: create.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ProjectController::create
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:40
 * @route "/projects/create"
 */
create.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: create.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\ProjectController::store
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:51
 * @route "/projects"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/projects",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ProjectController::store
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:51
 * @route "/projects"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::store
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:51
 * @route "/projects"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\ProjectController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:104
 * @route "/projects/{project}/edit"
 */
export const edit = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(args, options),
    method: "get",
})

edit.definition = {
    methods: ["get","head"],
    url: "/projects/{project}/edit",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ProjectController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:104
 * @route "/projects/{project}/edit"
 */
edit.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return edit.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:104
 * @route "/projects/{project}/edit"
 */
edit.get = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ProjectController::edit
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:104
 * @route "/projects/{project}/edit"
 */
edit.head = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: edit.url(args, options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\ProjectController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:128
 * @route "/projects/{project}"
 */
export const update = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put","patch"],
    url: "/projects/{project}",
} satisfies RouteDefinition<["put","patch"]>

/**
 * @see \App\Http\Controllers\ProjectController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:128
 * @route "/projects/{project}"
 */
update.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return update.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:128
 * @route "/projects/{project}"
 */
update.put = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\ProjectController::update
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:128
 * @route "/projects/{project}"
 */
update.patch = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})








/**
 * @see \App\Http\Controllers\ProjectController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:150
 * @route "/projects/{project}"
 */
export const destroy = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/projects/{project}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ProjectController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:150
 * @route "/projects/{project}"
 */
destroy.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return destroy.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::destroy
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:150
 * @route "/projects/{project}"
 */
destroy.delete = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})








/**
 * @see \App\Http\Controllers\ProjectController::restore
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:173
 * @route "/projects/{project}/restore"
 */
export const restore = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: restore.url(args, options),
    method: "post",
})

restore.definition = {
    methods: ["post"],
    url: "/projects/{project}/restore",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ProjectController::restore
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:173
 * @route "/projects/{project}/restore"
 */
restore.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return restore.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::restore
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:173
 * @route "/projects/{project}/restore"
 */
restore.post = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: restore.url(args, options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\ProjectController::duplicate
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:95
 * @route "/projects/{project}/duplicate"
 */
export const duplicate = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: duplicate.url(args, options),
    method: "post",
})

duplicate.definition = {
    methods: ["post"],
    url: "/projects/{project}/duplicate",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ProjectController::duplicate
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:95
 * @route "/projects/{project}/duplicate"
 */
duplicate.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return duplicate.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::duplicate
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:95
 * @route "/projects/{project}/duplicate"
 */
duplicate.post = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: duplicate.url(args, options),
    method: "post",
})









const projects = {
    index,
    create,
    store,
    edit,
    update,
    destroy,
    restore,
    duplicate,
    entries,
}

export default projects