// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";
import share from "./share";
import billing from "./billing";
import entries from "./entries";

/**
 * @see \App\Http\Controllers\ProjectController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:16
 * @route "/projects"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/projects",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ProjectController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:16
 * @route "/projects"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:16
 * @route "/projects"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ProjectController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:16
 * @route "/projects"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})








/**
 * @see \App\Http\Controllers\ProjectController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:46
 * @route "/projects"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/projects",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ProjectController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:46
 * @route "/projects"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::store
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:46
 * @route "/projects"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\ProjectController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:65
 * @route "/projects/{project}"
 */
export const update = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put","patch"],
    url: "/projects/{project}",
} satisfies RouteDefinition<["put","patch"]>

/**
 * @see \App\Http\Controllers\ProjectController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:65
 * @route "/projects/{project}"
 */
update.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return update.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:65
 * @route "/projects/{project}"
 */
update.put = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\ProjectController::update
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:65
 * @route "/projects/{project}"
 */
update.patch = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})








/**
 * @see \App\Http\Controllers\ProjectController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:74
 * @route "/projects/{project}"
 */
export const destroy = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/projects/{project}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ProjectController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:74
 * @route "/projects/{project}"
 */
destroy.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return destroy.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::destroy
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php:74
 * @route "/projects/{project}"
 */
destroy.delete = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})








/**
 * @see \App\Http\Controllers\TrackingController::updateBudget
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:119
 * @route "/projects/{project}/budget"
 */
export const budget = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: budget.url(args, options),
    method: "put",
})

budget.definition = {
    methods: ["put"],
    url: "/projects/{project}/budget",
} satisfies RouteDefinition<["put"]>

/**
 * @see \App\Http\Controllers\TrackingController::updateBudget
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:119
 * @route "/projects/{project}/budget"
 */
budget.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return budget.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\TrackingController::updateBudget
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:119
 * @route "/projects/{project}/budget"
 */
budget.put = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: budget.url(args, options),
    method: "put",
})









const projects = {
    index,
    store,
    update,
    destroy,
    budget,
    share,
    billing,
    entries,
}

export default projects