// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ExportSharedBillingHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ExportSharedBillingHandler.php:16
 * @route "/shares/{token}/export"
 */
export const exportMethod = (args: { token: string | number } | [ token: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: exportMethod.url(args, options),
    method: "get",
})

exportMethod.definition = {
    methods: ["get","head"],
    url: "/shares/{token}/export",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ExportSharedBillingHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ExportSharedBillingHandler.php:16
 * @route "/shares/{token}/export"
 */
exportMethod.url = (args: { token: string | number } | [ token: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { token: args }
    }
    
    if (Array.isArray(args)) {
        args = {
        token: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        token: args.token,
    }
    
    return exportMethod.definition.url
        .replace("{token}", parsedArgs.token.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ExportSharedBillingHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ExportSharedBillingHandler.php:16
 * @route "/shares/{token}/export"
 */
exportMethod.get = (args: { token: string | number } | [ token: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: exportMethod.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ExportSharedBillingHandler::__invoke
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ExportSharedBillingHandler.php:16
 * @route "/shares/{token}/export"
 */
exportMethod.head = (args: { token: string | number } | [ token: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: exportMethod.url(args, options),
    method: "head",
})









const billing = {
    export: exportMethod,
}

export default billing