// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\TrackingController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:16
 * @route "/tracking"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/tracking",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\TrackingController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:16
 * @route "/tracking"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\TrackingController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:16
 * @route "/tracking"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\TrackingController::index
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php:16
 * @route "/tracking"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})









const tracking = {
    index,
}

export default tracking