// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\SharedProjectController::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/SharedProjectController.php:17
 * @route "/shares/{share}/projects/{project}"
 */
export const show = (args: { share: string | { id: string }, project: string | { id: string } } | [ share: string | { id: string }, project: string | { id: string } ], options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/shares/{share}/projects/{project}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\SharedProjectController::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/SharedProjectController.php:17
 * @route "/shares/{share}/projects/{project}"
 */
show.url = (args: { share: string | { id: string }, project: string | { id: string } } | [ share: string | { id: string }, project: string | { id: string } ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
        args = {
        share: args[0],
        project: args[1],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        share: typeof args.share === "object" ? args.share.id : args.share,
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return show.definition.url
        .replace("{share}", parsedArgs.share.toString())
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\SharedProjectController::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/SharedProjectController.php:17
 * @route "/shares/{share}/projects/{project}"
 */
show.get = (args: { share: string | { id: string }, project: string | { id: string } } | [ share: string | { id: string }, project: string | { id: string } ], options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\SharedProjectController::__invoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/SharedProjectController.php:17
 * @route "/shares/{share}/projects/{project}"
 */
show.head = (args: { share: string | { id: string }, project: string | { id: string } } | [ share: string | { id: string }, project: string | { id: string } ], options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})









const projects = {
    show,
}

export default projects