// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import "@inertiajs/core";
import { Illuminate } from "./types";

declare module '@inertiajs/core' {
    export interface InertiaConfig {
     sharedPageProps: { auth: { user: Illuminate.Contracts.Auth.Authenticatable | null }, flash: { success: unknown }, csrfToken: string | null } 
    }
}