// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export namespace Inertia {
    export namespace Pages {
        /**
         * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
         */
        export type LoginPage = Inertia.SharedData & { users: App.Models.User[] | [], redirectUrl: string | null }

        /**
         * @see [\App\Http\Controllers\DashboardController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php)
         */
        export type DashboardPage = Inertia.SharedData & { entries: unknown, clients: unknown, projects: unknown }

        /**
         * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
         */
        export type ProfilePage = Inertia.SharedData & { user: { name: unknown, email: unknown, github_id: unknown } }

        /**
         * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
         */
        export type ProjectsPage = Inertia.SharedData & { projects: unknown, clients: unknown, open: boolean }

        /**
         * @see [\App\Http\Controllers\TimesheetHandler::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/TimesheetHandler.php)
         */
        export type TimesheetPage = Inertia.SharedData & { current: { year: number, month: number }, urls: { nextMonth: string, prevMonth: string }, projects: unknown, entries: unknown, holidays: [] }

        /**
         * @see [\App\Http\Controllers\TrackingController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php)
         */
        export type TrackingPage = Inertia.SharedData & { clients: unknown, selectedClientId: string | null | [] | null, projects: string[] }

        /**
         * @see [\App\Http\Controllers\ExportsController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
         */
        export type ExportPage = Inertia.SharedData & { allProjects: unknown, selectedProjectIds: unknown, dateStart: string, dateEnd: string, projects: [] }

        /**
         * @see [\App\Http\Controllers\SharedTimesheetController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/SharedTimesheetController.php)
         */
        export type SharedTimesheetPage = Inertia.SharedData & { month: unknown, shareToken: string, projectName: unknown, clientName: unknown, projectId: unknown, entries: unknown, holidays: [] }
    }
}

export namespace App {
    export namespace Http {
        export namespace Controllers {
            export namespace AuthController {
                export namespace Show {
                    /**
                     * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
                     */
                    export type Response = Inertia.Pages.LoginPage

                    /**
                     * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Disabled {
                    /**
                     * @see [\App\Http\Controllers\AuthController::disabled](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Logout {
                    /**
                     * @see [\App\Http\Controllers\AuthController::logout](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace DashboardController {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\DashboardController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php)
                     */
                    export type Response = Inertia.Pages.DashboardPage

                    /**
                     * @see [\App\Http\Controllers\DashboardController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace UserController {
                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
                     */
                    export type Response = Inertia.Pages.ProfilePage

                    /**
                     * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\UserController::update](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
                     */
                    export type Request = {    name: string;
                        email: string;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\UserController::destroy](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ProjectController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Response = Inertia.Pages.ProjectsPage

                    /**
                     * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::store](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = {    name: string;
                        description?: string | null;
                        daily_rate?: number | null;
                        client_id: string;
                        client_name?: string;
                        client_rate?: number;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::update](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = {    name: string;
                        description?: string | null;
                        daily_rate?: number | null;
                        client_id: string;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::destroy](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace TimesheetHandler {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\TimesheetHandler::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/TimesheetHandler.php)
                     */
                    export type Response = Inertia.Pages.TimesheetPage

                    /**
                     * @see [\App\Http\Controllers\TimesheetHandler::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/TimesheetHandler.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace TrackingController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\TrackingController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php)
                     */
                    export type Response = Inertia.Pages.TrackingPage

                    /**
                     * @see [\App\Http\Controllers\TrackingController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace StoreBilling {
                    /**
                     * @see [\App\Http\Controllers\TrackingController::storeBilling](/Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php)
                     */
                    export type Request = {    month: string;
                        amount_billed: number;
                        payment_date?: string | null;
                        notes?: string | null;}
                }

                export namespace UpdateBudget {
                    /**
                     * @see [\App\Http\Controllers\TrackingController::updateBudget](/Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php)
                     */
                    export type Request = {    max_budget?: number | null;}
                }

                export namespace UpdateBilling {
                    /**
                     * @see [\App\Http\Controllers\TrackingController::updateBilling](/Users/mathieutu/Projects/cra/app/Http/Controllers/TrackingController.php)
                     */
                    export type Request = {    amount_billed: number;
                        payment_date?: string | null;
                        notes?: string | null;}
                }
            }

            export namespace ExportsController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\ExportsController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
                     */
                    export type Response = Inertia.Pages.ExportPage

                    /**
                     * @see [\App\Http\Controllers\ExportsController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace ExportCsv {
                    /**
                     * @see [\App\Http\Controllers\ExportsController::exportCsv](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace ExportXlsx {
                    /**
                     * @see [\App\Http\Controllers\ExportsController::exportXlsx](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace SharedTimesheetController {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\SharedTimesheetController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/SharedTimesheetController.php)
                     */
                    export type Response = Inertia.Pages.SharedTimesheetPage

                    /**
                     * @see [\App\Http\Controllers\SharedTimesheetController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/SharedTimesheetController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ClientController {
                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\ClientController::store](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = {    name: string;
                        daily_rate: number;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\ClientController::update](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = {    name: string;
                        daily_rate: number;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\ClientController::destroy](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace TimesheetEntryController {
                export namespace Sync {
                    /**
                     * @see [\App\Http\Controllers\TimesheetEntryController::sync](/Users/mathieutu/Projects/cra/app/Http/Controllers/TimesheetEntryController.php)
                     */
                    export type Request = {    "*.coverage": number;
                        "*.title"?: string | null;
                        "*.description"?: string | null;}
                }
            }

            export namespace ProjectShareController {
                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\ProjectShareController::store](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectShareController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\ProjectShareController::destroy](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectShareController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }
        }
    }
}

export namespace Closure {
    export namespace __invoke {
        /**
         * @see [\Closure::__invoke](/Users/mathieutu/Projects/cra/vendor/laravel/boost/src/BoostServiceProvider.php)
         */
        export type Request = Record<string, unknown>
    }
}