// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export namespace Inertia {
    export namespace Pages {
        /**
         * @see [\App\Http\Controllers\ShowHomeHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowHomeHandler.php)
         */
        export type LandingPage = Inertia.SharedData

        /**
         * @see [\App\Http\Controllers\ShowHomeHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowHomeHandler.php)
         */
        export type DashboardPage = Inertia.SharedData & { from: string, to: string, firstEntryMonth: unknown, kpis: { monthDays: number, workingDays: boolean | null, fillRate: number, monthRevenue: number, projectedRevenue: number, periodRevenue: number, outstandingAmount: unknown, outstandingCount: unknown, overdueCount: unknown, periodWorkingDays: number, trendDays: number, trendRevenue: number, trendPeriod: number, prevPeriodRevenue: number, prevMonthRevenue: number }, chart: { labels: unknown, projects: unknown, billed: unknown, workingDays: unknown }, projects: unknown, monthAdvancement: number, outstandingInvoices: unknown, periodRevenueByClient: unknown }

        /**
         * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php)
         */
        export type LoginPage = Inertia.SharedData & { users: App.Models.User[] | [] }

        /**
         * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php)
         */
        export type ProfilePage = Inertia.SharedData & { user: unknown[] }

        /**
         * @see [\App\Http\Controllers\ClientController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
         */
        export type ClientForm = Inertia.SharedData & { page: [], modal: { client: unknown[] } }

        /**
         * @see [\App\Http\Controllers\ClientController::showBilling](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
         * @see [\App\Http\Controllers\ShowSharedHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowSharedHandler.php)
         */
        export type ProjectBillingPage = Inertia.SharedData & { projects: unknown, is_shared: false, shared_by?: unknown }

        /**
         * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
         */
        export type ProjectsPage = Inertia.SharedData

        /**
         * @see [\App\Http\Controllers\ProjectController::create](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
         * @see [\App\Http\Controllers\ProjectController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
         */
        export type ProjectForm = Inertia.SharedData & { page: [], modal: { project: string[] | null, clients: unknown } }

        /**
         * @see [\App\Http\Controllers\ShowTimesheetHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowTimesheetHandler.php)
         */
        export type TimesheetPage = Inertia.SharedData & { current: { year: number, month: number }, urls: { nextMonth: string, prevMonth: string }, holidays: [], invoices: unknown, projects: unknown }

        /**
         * @see [\App\Http\Controllers\ShowApiDocHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowApiDocHandler.php)
         */
        export type ApiDocPage = Inertia.SharedData & { base_url: Illuminate.Contracts.Routing.UrlGenerator | string, api_token: string | null, projects: unknown }
    }
}

export namespace App {
    export namespace Http {
        export namespace Controllers {
            export namespace ShowHomeHandler {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\ShowHomeHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowHomeHandler.php)
                     */
                    export type Response = Inertia.Pages.LandingPage | Inertia.Pages.DashboardPage

                    /**
                     * @see [\App\Http\Controllers\ShowHomeHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowHomeHandler.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace AuthController {
                export namespace Show {
                    /**
                     * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php)
                     */
                    export type Response = Inertia.Pages.LoginPage

                    /**
                     * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Demo {
                    /**
                     * @see [\App\Http\Controllers\AuthController::demo](/Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Redirect {
                    /**
                     * @see [\App\Http\Controllers\AuthController::redirect](/Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Callback {
                    /**
                     * @see [\App\Http\Controllers\AuthController::callback](/Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Disabled {
                    /**
                     * @see [\App\Http\Controllers\AuthController::disabled](/Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Logout {
                    /**
                     * @see [\App\Http\Controllers\AuthController::logout](/Users/mathieutu/Projects/takt/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace UserController {
                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php)
                     */
                    export type Response = Inertia.Pages.ProfilePage

                    /**
                     * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\UserController::update](/Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php)
                     */
                    export type Request = {    name: string;
                        email: string;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\UserController::destroy](/Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace RegenerateToken {
                    /**
                     * @see [\App\Http\Controllers\UserController::regenerateToken](/Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace DeleteToken {
                    /**
                     * @see [\App\Http\Controllers\UserController::deleteToken](/Users/mathieutu/Projects/takt/app/Http/Controllers/UserController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ClientController {
                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\ClientController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Response = Inertia.Pages.ClientForm

                    /**
                     * @see [\App\Http\Controllers\ClientController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace ShowBilling {
                    /**
                     * @see [\App\Http\Controllers\ClientController::showBilling](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Response = Inertia.Pages.ProjectBillingPage

                    /**
                     * @see [\App\Http\Controllers\ClientController::showBilling](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\ClientController::update](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = {    name: string;
                        daily_rate: number;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\ClientController::destroy](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Restore {
                    /**
                     * @see [\App\Http\Controllers\ClientController::restore](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace StoreShare {
                    /**
                     * @see [\App\Http\Controllers\ClientController::storeShare](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace DestroyShare {
                    /**
                     * @see [\App\Http\Controllers\ClientController::destroyShare](/Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ProjectController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Response = Inertia.Pages.ProjectsPage

                    /**
                     * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Create {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::create](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Response = Inertia.Pages.ProjectForm

                    /**
                     * @see [\App\Http\Controllers\ProjectController::create](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Response = Inertia.Pages.ProjectForm

                    /**
                     * @see [\App\Http\Controllers\ProjectController::edit](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace SyncEntries {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::syncEntries](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = {    entries: unknown[];
                        "entries.*.date": string;
                        "entries.*.coverage": number;
                        "entries.*.title"?: string | null;
                        "entries.*.description"?: string | null;}
                }

                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::store](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = {    name: string;
                        description?: string | null;
                        daily_rate?: number;
                        max_month_budget?: number | null;
                        max_total_budget?: number | null;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::update](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = {    name: string;
                        description?: string | null;
                        daily_rate?: number;
                        max_month_budget?: number | null;
                        max_total_budget?: number | null;
                        client_id: string;
                        start_date: string;
                        end_date?: string | null;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::destroy](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Duplicate {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::duplicate](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ShowTimesheetHandler {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\ShowTimesheetHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowTimesheetHandler.php)
                     */
                    export type Response = Inertia.Pages.TimesheetPage

                    /**
                     * @see [\App\Http\Controllers\ShowTimesheetHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowTimesheetHandler.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ShowApiDocHandler {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\ShowApiDocHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowApiDocHandler.php)
                     */
                    export type Response = Inertia.Pages.ApiDocPage

                    /**
                     * @see [\App\Http\Controllers\ShowApiDocHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowApiDocHandler.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace CommandBarController {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\CommandBarController::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/CommandBarController.php)
                     */
                    export type Response = { clients: unknown, projects: unknown }

                    /**
                     * @see [\App\Http\Controllers\CommandBarController::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/CommandBarController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ShowSharedHandler {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\ShowSharedHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowSharedHandler.php)
                     */
                    export type Response = Inertia.Pages.ProjectBillingPage

                    /**
                     * @see [\App\Http\Controllers\ShowSharedHandler::__invoke](/Users/mathieutu/Projects/takt/app/Http/Controllers/ShowSharedHandler.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ProjectInvoiceController {
                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\ProjectInvoiceController::store](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php)
                     */
                    export type Request = {    amount: number;
                        paid_at?: string | null;
                        notes?: string | null;
                        created_at: string;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\ProjectInvoiceController::update](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php)
                     */
                    export type Request = {    amount: number;
                        paid_at?: string | null;
                        notes?: string | null;
                        created_at: string;
                        project_id?: string;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\ProjectInvoiceController::destroy](/Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectInvoiceController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }
        }
    }
}

export namespace Closure {
    export namespace __invoke {
        /**
         * @see [\Closure::__invoke](/Users/mathieutu/Projects/takt/vendor/laravel/boost/src/BoostServiceProvider.php)
         */
        export type Request = Record<string, unknown>
    }
}