// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export namespace Inertia {
    export namespace Pages {
        /**
         * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
         */
        export type LoginPage = Inertia.SharedData & { users: App.Models.User[] | [], redirectUrl: string | null }

        /**
         * @see [\App\Http\Controllers\DashboardController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php)
         */
        export type DashboardPage = Inertia.SharedData & { entries: unknown, clients: unknown, projects: unknown }

        /**
         * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
         */
        export type ProfilePage = Inertia.SharedData & { user: { name: unknown, email: unknown, github_id: unknown } }

        /**
         * @see [\App\Http\Controllers\ClientController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
         */
        export type ClientForm = Inertia.SharedData & { page: [], modal: { client: unknown[] } }

        /**
         * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
         */
        export type ProjectsPage = Inertia.SharedData

        /**
         * @see [\App\Http\Controllers\ProjectController::create](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
         * @see [\App\Http\Controllers\ProjectController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
         */
        export type ProjectForm = Inertia.SharedData & { page: [], modal: { project: unknown[] | null, clients: unknown } }

        /**
         * @see [\App\Http\Controllers\BillingController::showClient](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
         * @see [\App\Http\Controllers\BillingController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
         * @see [\App\Http\Controllers\SharedController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/SharedController.php)
         */
        export type ProjectBillingPage = Inertia.SharedData & { projects: [][], is_shared: false, shared_by?: unknown }

        /**
         * @see [\App\Http\Controllers\TimesheetHandler::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/TimesheetHandler.php)
         */
        export type TimesheetPage = Inertia.SharedData & { current: { year: number, month: number }, urls: { nextMonth: string, prevMonth: string }, holidays: [], projects: unknown }

        /**
         * @see [\App\Http\Controllers\ExportsController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
         */
        export type ExportPage = Inertia.SharedData & { allProjects: unknown, selectedProjectIds: unknown, dateStart: string, dateEnd: string, projects: [] }
    }
}

export namespace App {
    export namespace Http {
        export namespace Controllers {
            export namespace AuthController {
                export namespace Show {
                    /**
                     * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
                     */
                    export type Response = Inertia.Pages.LoginPage

                    /**
                     * @see [\App\Http\Controllers\AuthController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Disabled {
                    /**
                     * @see [\App\Http\Controllers\AuthController::disabled](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Logout {
                    /**
                     * @see [\App\Http\Controllers\AuthController::logout](/Users/mathieutu/Projects/cra/app/Http/Controllers/AuthController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace DashboardController {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\DashboardController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php)
                     */
                    export type Response = Inertia.Pages.DashboardPage

                    /**
                     * @see [\App\Http\Controllers\DashboardController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/DashboardController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace UserController {
                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
                     */
                    export type Response = Inertia.Pages.ProfilePage

                    /**
                     * @see [\App\Http\Controllers\UserController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\UserController::update](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
                     */
                    export type Request = {    name: string;
                        email: string;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\UserController::destroy](/Users/mathieutu/Projects/cra/app/Http/Controllers/UserController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ClientController {
                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\ClientController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
                     */
                    export type Response = Inertia.Pages.ClientForm

                    /**
                     * @see [\App\Http\Controllers\ClientController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\ClientController::update](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = {    name: string;
                        daily_rate: number;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\ClientController::destroy](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Restore {
                    /**
                     * @see [\App\Http\Controllers\ClientController::restore](/Users/mathieutu/Projects/cra/app/Http/Controllers/ClientController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ProjectController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Response = Inertia.Pages.ProjectsPage

                    /**
                     * @see [\App\Http\Controllers\ProjectController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Create {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::create](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Response = Inertia.Pages.ProjectForm

                    /**
                     * @see [\App\Http\Controllers\ProjectController::create](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Edit {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Response = Inertia.Pages.ProjectForm

                    /**
                     * @see [\App\Http\Controllers\ProjectController::edit](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::store](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = {    name: string;
                        description?: string | null;
                        daily_rate?: number;
                        max_month_budget?: number | null;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::update](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = {    name: string;
                        description?: string | null;
                        daily_rate?: number;
                        max_month_budget?: number | null;
                        client_id: string;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::destroy](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Restore {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::restore](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Duplicate {
                    /**
                     * @see [\App\Http\Controllers\ProjectController::duplicate](/Users/mathieutu/Projects/cra/app/Http/Controllers/ProjectController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace BillingController {
                export namespace ShowClient {
                    /**
                     * @see [\App\Http\Controllers\BillingController::showClient](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
                     */
                    export type Response = Inertia.Pages.ProjectBillingPage

                    /**
                     * @see [\App\Http\Controllers\BillingController::showClient](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Show {
                    /**
                     * @see [\App\Http\Controllers\BillingController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
                     */
                    export type Response = Inertia.Pages.ProjectBillingPage

                    /**
                     * @see [\App\Http\Controllers\BillingController::show](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace Store {
                    /**
                     * @see [\App\Http\Controllers\BillingController::store](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
                     */
                    export type Request = {    amount: number;
                        paid_at?: string | null;
                        notes?: string | null;}
                }

                export namespace Update {
                    /**
                     * @see [\App\Http\Controllers\BillingController::update](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
                     */
                    export type Request = {    amount: number;
                        paid_at?: string | null;
                        notes?: string | null;}
                }

                export namespace Destroy {
                    /**
                     * @see [\App\Http\Controllers\BillingController::destroy](/Users/mathieutu/Projects/cra/app/Http/Controllers/BillingController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace TimesheetHandler {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\TimesheetHandler::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/TimesheetHandler.php)
                     */
                    export type Response = Inertia.Pages.TimesheetPage

                    /**
                     * @see [\App\Http\Controllers\TimesheetHandler::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/TimesheetHandler.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace ExportsController {
                export namespace Index {
                    /**
                     * @see [\App\Http\Controllers\ExportsController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
                     */
                    export type Response = Inertia.Pages.ExportPage

                    /**
                     * @see [\App\Http\Controllers\ExportsController::index](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace ExportCsv {
                    /**
                     * @see [\App\Http\Controllers\ExportsController::exportCsv](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace ExportXlsx {
                    /**
                     * @see [\App\Http\Controllers\ExportsController::exportXlsx](/Users/mathieutu/Projects/cra/app/Http/Controllers/ExportsController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace SharedController {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\SharedController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/SharedController.php)
                     */
                    export type Response = Inertia.Pages.ProjectBillingPage

                    /**
                     * @see [\App\Http\Controllers\SharedController::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/SharedController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }

            export namespace SyncProjectEntriesHandler {
                export namespace __invoke {
                    /**
                     * @see [\App\Http\Controllers\SyncProjectEntriesHandler::__invoke](/Users/mathieutu/Projects/cra/app/Http/Controllers/SyncProjectEntriesHandler.php)
                     */
                    export type Request = {    "*.coverage": number;
                        "*.title"?: string | null;
                        "*.description"?: string | null;}
                }
            }

            export namespace ShareController {
                export namespace StoreClient {
                    /**
                     * @see [\App\Http\Controllers\ShareController::storeClient](/Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php)
                     */
                    export type Request = Record<string, unknown>
                }

                export namespace DestroyClient {
                    /**
                     * @see [\App\Http\Controllers\ShareController::destroyClient](/Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php)
                     */
                    export type Request = Record<string, unknown>
                }
            }
        }
    }
}

export namespace Closure {
    export namespace __invoke {
        /**
         * @see [\Closure::__invoke](/Users/mathieutu/Projects/cra/vendor/laravel/boost/src/BoostServiceProvider.php)
         */
        export type Request = Record<string, unknown>
    }
}