// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ShareController::storeProject
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:13
 * @route "/projects/{project}/share"
 */
export const store = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/projects/{project}/share",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\ShareController::storeProject
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:13
 * @route "/projects/{project}/share"
 */
store.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return store.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ShareController::storeProject
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:13
 * @route "/projects/{project}/share"
 */
store.post = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})








/**
 * @see \App\Http\Controllers\ShareController::destroyProject
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:18
 * @route "/projects/{project}/share"
 */
export const destroy = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/projects/{project}/share",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ShareController::destroyProject
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:18
 * @route "/projects/{project}/share"
 */
destroy.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return destroy.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ShareController::destroyProject
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:18
 * @route "/projects/{project}/share"
 */
destroy.delete = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})









const share = {
    store,
    destroy,
}

export default share