// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ShareController::revoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:26
 * @route "/projects/{project}/share"
 */
export const revoke = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: revoke.url(args, options),
    method: "delete",
})

revoke.definition = {
    methods: ["delete"],
    url: "/projects/{project}/share",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\ShareController::revoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:26
 * @route "/projects/{project}/share"
 */
revoke.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return revoke.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ShareController::revoke
 * @see /Users/mathieutu/Projects/cra/app/Http/Controllers/ShareController.php:26
 * @route "/projects/{project}/share"
 */
revoke.delete = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: revoke.url(args, options),
    method: "delete",
})









const share = {
    revoke,
}

export default share