// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ClientController::showBilling
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:70
 * @route "/clients/{client}/billing"
 */
export const show = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/clients/{client}/billing",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\ClientController::showBilling
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:70
 * @route "/clients/{client}/billing"
 */
show.url = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { client: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { client: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        client: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        client: typeof args.client === "object" ? args.client.id : args.client,
    }
    
    return show.definition.url
        .replace("{client}", parsedArgs.client.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ClientController::showBilling
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:70
 * @route "/clients/{client}/billing"
 */
show.get = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\ClientController::showBilling
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ClientController.php:70
 * @route "/clients/{client}/billing"
 */
show.head = (args: { client: string | { id: string } } | [ client: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})









const billing = {
    show,
}

export default billing