// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\ProjectController::syncEntries
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:184
 * @route "/projects/{project}/entries"
 */
export const sync = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: sync.url(args, options),
    method: "patch",
})

sync.definition = {
    methods: ["patch"],
    url: "/projects/{project}/entries",
} satisfies RouteDefinition<["patch"]>

/**
 * @see \App\Http\Controllers\ProjectController::syncEntries
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:184
 * @route "/projects/{project}/entries"
 */
sync.url = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { project: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { project: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        project: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        project: typeof args.project === "object" ? args.project.id : args.project,
    }
    
    return sync.definition.url
        .replace("{project}", parsedArgs.project.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\ProjectController::syncEntries
 * @see /Users/mathieutu/Projects/takt/app/Http/Controllers/ProjectController.php:184
 * @route "/projects/{project}/entries"
 */
sync.patch = (args: { project: string | { id: string } } | [ project: string | { id: string } ] | string | { id: string }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: sync.url(args, options),
    method: "patch",
})









const entries = {
    sync,
}

export default entries