// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see /Users/mathieutu/Projects/cra/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemServiceProvider.php:106
 * @route "/storage/{path}"
 */
export const upload = (args: { path: string | number } | [ path: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: upload.url(args, options),
    method: "put",
})

upload.definition = {
    methods: ["put"],
    url: "/storage/{path}",
} satisfies RouteDefinition<["put"]>

/**
 * @see /Users/mathieutu/Projects/cra/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemServiceProvider.php:106
 * @route "/storage/{path}"
 */
upload.url = (args: { path: string | number } | [ path: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { path: args }
    }
    
    if (Array.isArray(args)) {
        args = {
        path: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        path: args.path,
    }
    
    return upload.definition.url
        .replace("{path}", parsedArgs.path.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see /Users/mathieutu/Projects/cra/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemServiceProvider.php:106
 * @route "/storage/{path}"
 */
upload.put = (args: { path: string | number } | [ path: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: upload.url(args, options),
    method: "put",
})









const local = {
    upload,
}

export default local