// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import projects from "./projects";

export const api = {
    projects,
}

export default api